# SQL in Python

In [52]:
# Imports

import sqlite3
import pandas as pd

In [53]:
# Load data

data = pd.read_csv('https://raw.githubusercontent.com/renatomaaliw3/public_files/master/Data%20Sets/summer.csv')
data.head(5)

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1896,Athens,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100M Freestyle,Gold
1,1896,Athens,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100M Freestyle,Silver
2,1896,Athens,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100M Freestyle For Sailors,Bronze
3,1896,Athens,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100M Freestyle For Sailors,Gold
4,1896,Athens,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100M Freestyle For Sailors,Silver

In [54]:
# Connect to an in memory SQLite Database

conn = sqlite3.connect(':memory')

In [55]:
# Write the DataFrame to the Database

data.to_sql('Summer', conn, iindex = False, if_exists = 'replace')

31165

In [56]:
# Execute a SQL Query

query = "SELECT * FROM Summer"

result_sql = pd.read_sql_query(query, conn)
result_sql

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1896,Athens,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100M Freestyle,Gold
1,1896,Athens,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100M Freestyle,Silver
2,1896,Athens,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100M Freestyle For Sailors,Bronze
3,1896,Athens,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100M Freestyle For Sailors,Gold
4,1896,Athens,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100M Freestyle For Sailors,Silver
...,...,...,...,...,...,...,...,...,...
31160,2012,London,Wrestling,Wrestling Freestyle,"JANIKOWSKI, Damian",POL,Men,Wg 84 KG,Bronze
31161,2012,London,Wrestling,Wrestling Freestyle,"REZAEI, Ghasem Gholamreza",IRI,Men,Wg 96 KG,Gold
31162,2012,London,Wrestling,Wrestling Freestyle,"TOTROV, Rustam",RUS,Men,Wg 96 KG,Silver
31163,2012,London,Wrestling,Wrestling Freestyle,"ALEKSANYAN, Artur",ARM,Men,Wg 96 KG,Bronze
31164,2012,London,Wrestling,Wrestling Freestyle,"LIDBERG, Jimmy",SWE,Men,Wg 96 KG,Bronze

In [57]:
# Notes

# 00. SELECT (Extract)
# 0. AS (Alias)
# 1. WHERE (Certain conditions), NOT, AND, OR Comparison Operator (<,>,=, etc.)
# 2. ORDER BY, By DEFAULT ASC
# 3. LIKE (Wildcard -> For String), %, _
# 4. GROUP BY, HAVING (Aggregation Function)
# 5. (AVG, COUNT, SUM, MAX, MIN), (DISTINCT) -> unique
# 6. IN
# 7. BETWEEN
# 8. UNION, etc.

In [58]:
# Specific Columns

query = "SELECT City, Athlete FROM Summer"
result_sql = pd.read_sql_query(query, conn)
result_sql

         City                    Athlete
0      Athens              HAJOS, Alfred
1      Athens           HERSCHMANN, Otto
2      Athens          DRIVAS, Dimitrios
3      Athens         MALOKINIS, Ioannis
4      Athens         CHASAPIS, Spiridon
...       ...                        ...
31160  London         JANIKOWSKI, Damian
31161  London  REZAEI, Ghasem Gholamreza
31162  London             TOTROV, Rustam
31163  London          ALEKSANYAN, Artur
31164  London             LIDBERG, Jimmy

[31165 rows x 2 columns]

In [59]:
# Alias

query = "SELECT City, Athlete AS 'Full Name' FROM Summer"
result_sql = pd.read_sql_query(query, conn)
result_sql

         City                  Full Name
0      Athens              HAJOS, Alfred
1      Athens           HERSCHMANN, Otto
2      Athens          DRIVAS, Dimitrios
3      Athens         MALOKINIS, Ioannis
4      Athens         CHASAPIS, Spiridon
...       ...                        ...
31160  London         JANIKOWSKI, Damian
31161  London  REZAEI, Ghasem Gholamreza
31162  London             TOTROV, Rustam
31163  London          ALEKSANYAN, Artur
31164  London             LIDBERG, Jimmy

[31165 rows x 2 columns]

In [60]:
# WHERE

query = "SELECT * FROM Summer WHERE Event = '100M Freestyle' AND Medal = 'Gold' AND Country = 'USA' AND Gender = 'Men'"
result_sql = pd.read_sql_query(query, conn)
result_sql

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1908,London,Aquatics,Swimming,"DANIELS, Charles",USA,Men,100M Freestyle,Gold
1,1912,Stockholm,Aquatics,Swimming,"KAHANAMOKU, Duke Paoa",USA,Men,100M Freestyle,Gold
2,1920,Antwerp,Aquatics,Swimming,"KAHANAMOKU, Duke Paoa",USA,Men,100M Freestyle,Gold
3,1924,Paris,Aquatics,Swimming,"WEISSMULLER, Johnny",USA,Men,100M Freestyle,Gold
4,1928,Amsterdam,Aquatics,Swimming,"WEISSMULLER, Johnny",USA,Men,100M Freestyle,Gold
5,1948,London,Aquatics,Swimming,"RIS, Walter Stephen",USA,Men,100M Freestyle,Gold
6,1952,Helsinki,Aquatics,Swimming,"SCHOLES, Clark Currie",USA,Men,100M Freestyle,Gold
7,1964,Tokyo,Aquatics,Swimming,"SCHOLLANDER, Donald Arthur",USA,Men,100M Freestyle,Gold
8,1972,Munich,Aquatics,Swimming,"SPITZ, Mark",USA,Men,100M Freestyle,Gold
9,1976,Montreal,Aquatics,Swimming,"MONTGOMERY, James Paul",USA,Men,100M Freestyle,Gold
10,1984,Los Angeles,Aquatics,Swimming,"GAINES, Ambrose Iv",USA,Men,100M Freestyle,Gold
11,1988,Seoul,Aquatics,Swimming,"BIONDI, Matthew",USA,Men,100M Freestyle,Gold
12,2012,London,Aquatics,Swimming,"ADRIAN, Nathan",USA,Men,100M Freestyle,Gold

In [90]:
# ORDER BY

query = "SELECT * FROM Summer WHERE Event = '100M Freestyle'"
query += " AND Medal = 'Gold' AND Country = 'USA' AND Gender = 'Men' ORDER BY Athlete DESC"
result_sql = pd.read_sql_query(query, conn)
result_sql

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1924,Paris,Aquatics,Swimming,"WEISSMULLER, Johnny",USA,Men,100M Freestyle,Gold
1,1928,Amsterdam,Aquatics,Swimming,"WEISSMULLER, Johnny",USA,Men,100M Freestyle,Gold
2,1972,Munich,Aquatics,Swimming,"SPITZ, Mark",USA,Men,100M Freestyle,Gold
3,1964,Tokyo,Aquatics,Swimming,"SCHOLLANDER, Donald Arthur",USA,Men,100M Freestyle,Gold
4,1952,Helsinki,Aquatics,Swimming,"SCHOLES, Clark Currie",USA,Men,100M Freestyle,Gold
5,1948,London,Aquatics,Swimming,"RIS, Walter Stephen",USA,Men,100M Freestyle,Gold
6,1976,Montreal,Aquatics,Swimming,"MONTGOMERY, James Paul",USA,Men,100M Freestyle,Gold
7,1912,Stockholm,Aquatics,Swimming,"KAHANAMOKU, Duke Paoa",USA,Men,100M Freestyle,Gold
8,1920,Antwerp,Aquatics,Swimming,"KAHANAMOKU, Duke Paoa",USA,Men,100M Freestyle,Gold
9,1984,Los Angeles,Aquatics,Swimming,"GAINES, Ambrose Iv",USA,Men,100M Freestyle,Gold
10,1908,London,Aquatics,Swimming,"DANIELS, Charles",USA,Men,100M Freestyle,Gold
11,1988,Seoul,Aquatics,Swimming,"BIONDI, Matthew",USA,Men,100M Freestyle,Gold
12,2012,London,Aquatics,Swimming,"ADRIAN, Nathan",USA,Men,100M Freestyle,Gold

In [62]:
# LIMIT

query = "SELECT * FROM Summer WHERE Event = '100M Freestyle' AND Medal = 'Gold' AND Country = 'USA'"
query += " AND Gender = 'Men' ORDER BY Athlete DESC LIMIT 3"

result_sql = pd.read_sql_query(query, conn)
result_sql

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1924,Paris,Aquatics,Swimming,"WEISSMULLER, Johnny",USA,Men,100M Freestyle,Gold
1,1928,Amsterdam,Aquatics,Swimming,"WEISSMULLER, Johnny",USA,Men,100M Freestyle,Gold
2,1972,Munich,Aquatics,Swimming,"SPITZ, Mark",USA,Men,100M Freestyle,Gold

In [63]:
# LIKE (Wildcard %)

query = "SELECT * FROM Summer WHERE Athlete LIKE '%kyo%' AND Gender = 'Men'"
result_sql = pd.read_sql_query(query, conn)
result_sql

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1968,Mexico,Boxing,Boxing,"CHANG, Kyou-Chul",KOR,Men,51 - 54KG (Bantamweight),Bronze
1,1984,Los Angeles,Gymnastics,Artistic G.,"YAMAWAKI, Kyoji",JPN,Men,Team Competition,Bronze
2,1996,Atlanta,Archery,Archery,"OH, Kyo-Moon",KOR,Men,Individual (Fita Olympic Round - 70M),Bronze
3,1996,Atlanta,Archery,Archery,"OH, Kyo-Moon",KOR,Men,Team (Fita Olympic Round - 70M),Silver
4,2000,Sydney,Archery,Archery,"OH, Kyo-Moon",KOR,Men,Team (Fita Olympic Round - 70M),Gold
5,2000,Sydney,Taekwondo,Taekwondo,"KIM, Kyong-Hun",KOR,Men,+ 80 KG,Gold
6,2012,London,Football,Football,"YUN, Sukyoung",KOR,Men,Football,Bronze
7,2012,London,Wrestling,Wrestling Freestyle,"YANG, Kyong Il",PRK,Men,Wf 55 KG,Bronze

In [74]:
# LIKE (Wildcard _) - Exact

query = "SELECT * FROM Summer WHERE Athlete LIKE '_______' AND Gender = 'Men'"
result_sql = pd.read_sql_query(query, conn)
result_sql

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1900,Paris,Aquatics,Swimming,TARTARA,FRA,Men,200M Team Swimming,Bronze
1,1900,Paris,Aquatics,Water polo,DEVENOT,FRA,Men,Water Polo,Bronze
2,1900,Paris,Aquatics,Water polo,LERICHE,FRA,Men,Water Polo,Bronze
3,1900,Paris,Football,Football,FRAYSSE,FRA,Men,Football,Silver
4,1900,Paris,Football,Football,LAMBERT,FRA,Men,Football,Silver
5,1900,Paris,Football,Football,MACAIRE,FRA,Men,Football,Silver
6,1900,Paris,Football,Football,PELTIER,FRA,Men,Football,Silver
7,1900,Paris,Rowing,Rowing,CHARLOT,FRA,Men,Four-Oared Shell With Coxswain (4-),Gold
8,1900,Paris,Shooting,Shooting,TRINITE,FRA,Men,"50M Army Pistol, Team",Silver
9,1904,St Louis,Football,Football,DIERKES,USA,Men,Football,Bronze
10,1904,St Louis,Football,Football,DIERKES,USA,Men,Football,Gold
11,1980,Moscow,Equestrian,Dressage,DECEBAL,ROU,Men,Team,Bronze
12,1980,Moscow,Equestrian,Dressage,DERBIST,ROU,Men,Team,Bronze
13,1980,Moscow,Equestrian,Dressage,SCHIBOR,BUL,Men,Team,Silver
14,1980,Moscow,Equestrian,Eventing,PINTSET,URS,Men,Individual,Bronze
15,1980,Moscow,Equestrian,Eventing,PINTSET,URS,Men,Team,Gold
16,1980,Moscow,Equestrian,Eventing,TSKHETI,URS,Men,Team,Gold
17,1980,Moscow,Equestrian,Jumping,GEPATIT,URS,Men,Team,Gold
18,1992,Barcelona,Table Tennis,Table Tennis,"LU, Lin",CHN,Men,Doubles,Gold
19,1992,Barcelona,Wrestling,Wrestling Free.,"KIM, Il",PRK,Men,- 48KG (Light-Flyweight),Gold
20,1996,Atlanta,Football,Football,DANRLEI,BRA,Men,Football,Bronze
21,1996,Atlanta,Football,Football,JUNINHO,BRA,Men,Football,Bronze
22,1996,Atlanta,Football,Football,NARCISO,BRA,Men,Football,Bronze
23,1996,Atlanta,Football,Football,RIVALDO,BRA,Men,Football,Bronze
24,1996,Atlanta,Table Tennis,Table Tennis,"LU, Lin",CHN,Men,Doubles,Silver
25,1996,Atlanta,Wrestling,Wrestling Free.,"KIM, Il",PRK,Men,- 48KG (Light-Flyweight),Gold
26,2000,Sydney,Aquatics,Diving,"HU, Jia",CHN,Men,10M Platform,Silver
27,2000,Sydney,Aquatics,Diving,"HU, Jia",CHN,Men,Synchronized Diving 10M Platform,Silver
28,2004,Athens,Aquatics,Diving,"HU, Jia",CHN,Men,10M Platform,Gold
29,2004,Athens,Shooting,Shooting,"LI, Jie",CHN,Men,10M Air Rifle (60 Shots),Silver
30,2004,Athens,Table Tennis,Table Tennis,"MA, Lin",CHN,Men,Doubles,Gold
31,2008,Beijing,Football,Football,ILSINHO,BRA,Men,Football,Bronze
32,2008,Beijing,Football,Football,MARCELO,BRA,Men,Football,Bronze
33,2008,Beijing,Football,Football,RAFINHA,BRA,Men,Football,Bronze
34,2008,Beijing,Football,Football,RAMIRES,BRA,Men,Football,Bronze
35,2008,Beijing,Table Tennis,Table Tennis,"MA, Lin",CHN,Men,Singles,Gold
36,2008,Beijing,Table Tennis,Table Tennis,"MA, Lin",CHN,Men,Team,Gold
37,2012,London,Aquatics,Diving,"QIU, Bo",CHN,Men,10M Platform,Silver
38,2012,London,Football,Football,GABRIEL,BRA,Men,Football,Silver
39,2012,London,Football,Football,MARCELO,BRA,Men,Football,Silver
40,2012,London,Weightlifting,Weightlifting,Pending,None,Men,94KG,Silver

In [79]:
# LIKE (Wildcard _)

query = "SELECT * FROM Summer WHERE Athlete LIKE 'A____R%' AND Gender = 'Men'"
result_sql = pd.read_sql_query(query, conn)
result_sql

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1904,St Louis,Athletics,Athletics,"ASHBURNER, Lesley",USA,Men,110M Hurdles,Bronze
1,1904,St Louis,Rowing,Rowing,"ARMSTRONG, Charles E.",USA,Men,Eight With Coxswain (8+),Gold
2,1908,London,Fencing,Fencing,"ALIBERT, Gaston",FRA,Men,Épée Individual,Gold
3,1908,London,Fencing,Fencing,"ALIBERT, Gaston",FRA,Men,Épée Team,Gold
4,1912,Stockholm,Sailing,Sailing,"AHNGER, Arthur",FIN,Men,8M,Bronze
5,1920,Antwerp,Archery,Archery,"ALLAERT, Alphonse",BEL,Men,Moving Bird Target 28M Teams,Silver
6,1920,Antwerp,Archery,Archery,"ALLAERT, Alphonse",BEL,Men,Moving Bird Target 33M Teams,Gold
7,1920,Antwerp,Archery,Archery,"ALLAERT, Alphonse",BEL,Men,Moving Bird Target 50M Teams,Gold
8,1920,Antwerp,Equestrian,Eventing,"ASINARI, Carlo",ITA,Men,Team,Silver
9,1920,Antwerp,Fencing,Fencing,"ABELARDO, Olivier",ITA,Men,Épée Team,Gold
10,1920,Antwerp,Fencing,Fencing,"ABELARDO, Olivier",ITA,Men,Foil Team,Gold
11,1920,Antwerp,Shooting,Shooting,"AMOUDRUZ, Gustave",SUI,Men,"30M Army Pistol, Team",Bronze
12,1920,Antwerp,Tennis,Tennis,"ALBARRAN, Pierre",FRA,Men,Doubles,Bronze
13,1924,Paris,Weightlifting,Weightlifting,"AIGNER, Franz",AUT,Men,"+ 82.5KG, One-Two Hand 5 Events (Heavyweight)",Silver
14,1924,Paris,Wrestling,Wrestling Gre-R,"AHLFORS, Anselm",FIN,Men,- 58KG (Bantamweight),Silver
15,1932,Los Angeles,Boxing,Boxing,"AHLBERG, Bruno Valfrid",FIN,Men,61.24 - 66.68KG (Welterweight),Bronze
16,1932,Los Angeles,Sailing,Sailing,"ASTHER, Gunnar Anton Edvard",SWE,Men,Two-Person Keelboat Open (Star),Bronze
17,1948,London,Athletics,Athletics,"ARCHER, John",GBR,Men,4X100M Relay,Silver
18,1948,London,Boxing,Boxing,"ARTHUR, John",RSA,Men,+ 80KG (Heavyweight),Bronze
19,1948,London,Hockey,Hockey,"AHKTAR, Hussain",IND,Men,Hockey,Gold
20,1948,London,Wrestling,Wrestling Free.,"ARMSTRONG, Joseph",AUS,Men,+ 87KG (Heavyweight),Bronze
21,1956,Melbourne / Stockholm,Hockey,Hockey,"AHKTAR, Hussain",PAK,Men,Hockey,Silver
22,1964,Tokyo,Athletics,Athletics,"ASHWORTH, Gerald Howard",USA,Men,4X100M Relay,Gold
23,1964,Tokyo,Athletics,Athletics,"AUN, Rein",URS,Men,Decathlon,Silver
24,1968,Mexico,Sailing,Sailing,"AISHER, Robin Allingham",GBR,Men,5.5M,Bronze
25,1972,Munich,Hockey,Hockey,"AKHTAR, Rasool",PAK,Men,Hockey,Silver
26,1972,Munich,Hockey,Hockey,"AKHTAR, Ul Islam",PAK,Men,Hockey,Silver
27,1976,Montreal,Basketball,Basketball,"ARMSTRONG, Michael Taylor (Tate)",USA,Men,Basketball,Gold
28,1976,Montreal,Hockey,Hockey,"AKHTAR, Rasool",PAK,Men,Hockey,Bronze
29,1984,Los Angeles,Aquatics,Swimming,"ASTBURY, Andrew",GBR,Men,4X200M Freestyle Relay,Bronze
30,1988,Seoul,Aquatics,Swimming,"ARMSTRONG, Duncan John",AUS,Men,200M Freestyle,Gold
31,1988,Seoul,Aquatics,Swimming,"ARMSTRONG, Duncan John",AUS,Men,400M Freestyle,Silver
32,1988,Seoul,Cycling,Cycling Road,"AMPLER, Uwe",GDR,Men,Team Time Trial,Gold
33,1996,Atlanta,Football,Football,ALDAIR,BRA,Men,Football,Bronze
34,2000,Sydney,Badminton,Badminton,"ARCHER, Simon",GBR,Men,Doubles,Bronze
35,2000,Sydney,Cycling,Cycling Road,"ARMSTRONG, Lance E.",USA,Men,Individual Time Trial,Bronze
36,2000,Sydney,Shooting,Shooting,"ALIFIRENKO, Sergei",RUS,Men,25M Rapid Fire Pistol (60 Shots),Gold
37,2004,Athens,Shooting,Shooting,"ALIFIRENKO, Sergei",RUS,Men,25M Rapid Fire Pistol (60 Shots),Bronze
38,2008,Beijing,Athletics,Athletics,"ASAHARA, Nobuharu",JPN,Men,4X100M Relay,Bronze
39,2008,Beijing,Football,Football,"AJILORE, Ebenezer",NGR,Men,Football,Silver
40,2008,Beijing,Handball,Handball,"ASGEIRSSON, Sturla",ISL,Men,Handball,Silver
41,2012,London,Canoe,Canoe Slalom,"AIGNER, Hannes",GER,Men,K-1 (Single),Bronze

In [85]:
# GROUP BY, Aggregation Function, COUNT, MAX, MIN, AVG, SUM)

query = "SELECT Country, COUNT(Medal) AS 'Medal Count' FROM Summer GROUP BY Country ORDER BY Count(Medal)"
result_sql = pd.read_sql_query(query, conn)
result_sql

    Country  Medal Count
0       AHO            1
1       BAR            1
2       BDI            1
3       BER            1
4       BOT            1
..      ...          ...
143     GER         1305
144     FRA         1396
145     GBR         1720
146     URS         2049
147     USA         4585

[148 rows x 2 columns]

In [80]:
# GROUP BY, HAVING (Aggregation Function, COUNT, MAX, MIN, AVG, SUM)

query = "SELECT Country, COUNT(Medal) AS 'Medal Count' FROM Summer"
query += " GROUP BY Country HAVING Country = 'USA' OR Country = 'PHI' ORDER BY Count(Medal) DESC"
result_sql = pd.read_sql_query(query, conn)
result_sql

  Country  Medal Count
0     USA         4585
1     PHI            9

In [68]:
# DISTINCT

query = "SELECT DISTINCT(Country) FROM Summer"
result_sql = pd.read_sql_query(query, conn)
result_sql

    Country
0       HUN
1       AUT
2       GRE
3       USA
4       GER
..      ...
143     BOT
144     MNE
145     CYP
146     SGP
147     GAB

[148 rows x 1 columns]

In [69]:
# DISTINCT

query = "SELECT COUNT(DISTINCT(Country)) AS 'Participating Country' FROM Summer"
result_sql = pd.read_sql_query(query, conn)
result_sql

   Participating Country
0                    147

In [70]:
# IN (Shorthand OR), Can be used in WHERE or HAVING

query = "SELECT Country, COUNT(Athlete) FROM Summer GROUP BY Country HAVING Country IN ('USA', 'AUS', 'CAN')"
result_sql = pd.read_sql_query(query, conn)
result_sql

  Country  COUNT(Athlete)
0     AUS            1189
1     CAN             649
2     USA            4585

In [88]:
# BETWEEN (Shorthand for Ranges), Can be used in WHERE or HAVING

query = "SELECT Year, Athlete, Event FROM Summer WHERE Year BETWEEN 1896 AND 1912 AND (Event = '100M Freestyle')"
result_sql = pd.read_sql_query(query, conn)
result_sql

    Year                Athlete           Event
0   1896          HAJOS, Alfred  100M Freestyle
1   1896       HERSCHMANN, Otto  100M Freestyle
2   1904        LEARY, J. Scott  100M Freestyle
3   1904         HALMAY, Zoltan  100M Freestyle
4   1904       DANIELS, Charles  100M Freestyle
5   1908     JULIN, Harald S.A.  100M Freestyle
6   1908       DANIELS, Charles  100M Freestyle
7   1908         HALMAY, Zoltan  100M Freestyle
8   1912       HUSZAGH, Kenneth  100M Freestyle
9   1912  KAHANAMOKU, Duke Paoa  100M Freestyle
10  1912           HEALY, Cecil  100M Freestyle
11  1912       FLETCHER, Jennie  100M Freestyle
12  1912          DURACK, Fanny  100M Freestyle
13  1912      WYLIE, Wilhelmina  100M Freestyle