# SQL in Python

In [8]:
# Imports

import sqlite3
import pandas as pd

In [9]:
# Load data

data = pd.read_csv('https://raw.githubusercontent.com/renatomaaliw3/public_files/master/Data%20Sets/summer.csv')
data

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1896,Athens,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100M Freestyle,Gold
1,1896,Athens,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100M Freestyle,Silver
2,1896,Athens,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100M Freestyle For Sailors,Bronze
3,1896,Athens,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100M Freestyle For Sailors,Gold
4,1896,Athens,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100M Freestyle For Sailors,Silver
...,...,...,...,...,...,...,...,...,...
31160,2012,London,Wrestling,Wrestling Freestyle,"JANIKOWSKI, Damian",POL,Men,Wg 84 KG,Bronze
31161,2012,London,Wrestling,Wrestling Freestyle,"REZAEI, Ghasem Gholamreza",IRI,Men,Wg 96 KG,Gold
31162,2012,London,Wrestling,Wrestling Freestyle,"TOTROV, Rustam",RUS,Men,Wg 96 KG,Silver
31163,2012,London,Wrestling,Wrestling Freestyle,"ALEKSANYAN, Artur",ARM,Men,Wg 96 KG,Bronze
31164,2012,London,Wrestling,Wrestling Freestyle,"LIDBERG, Jimmy",SWE,Men,Wg 96 KG,Bronze

In [10]:
# Connect to an in memory SQLite Database

conn = sqlite3.connect(':memory')

In [11]:
# Write the DataFrame to the Database

data.to_sql('Summer', conn, index = False, if_exists = 'replace')

31165

In [12]:
# Execute a SQL Query

query = "SELECT * FROM Summer"

result_sql = pd.read_sql_query(query, conn)
result_sql

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1896,Athens,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100M Freestyle,Gold
1,1896,Athens,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100M Freestyle,Silver
2,1896,Athens,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100M Freestyle For Sailors,Bronze
3,1896,Athens,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100M Freestyle For Sailors,Gold
4,1896,Athens,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100M Freestyle For Sailors,Silver
...,...,...,...,...,...,...,...,...,...
31160,2012,London,Wrestling,Wrestling Freestyle,"JANIKOWSKI, Damian",POL,Men,Wg 84 KG,Bronze
31161,2012,London,Wrestling,Wrestling Freestyle,"REZAEI, Ghasem Gholamreza",IRI,Men,Wg 96 KG,Gold
31162,2012,London,Wrestling,Wrestling Freestyle,"TOTROV, Rustam",RUS,Men,Wg 96 KG,Silver
31163,2012,London,Wrestling,Wrestling Freestyle,"ALEKSANYAN, Artur",ARM,Men,Wg 96 KG,Bronze
31164,2012,London,Wrestling,Wrestling Freestyle,"LIDBERG, Jimmy",SWE,Men,Wg 96 KG,Bronze

In [13]:
# Notes

# 00. SELECT (Extract)
# 0. AS (Alias)
# 1. WHERE (Certain conditions), NOT, AND, OR Comparison Operator (<,>,=, etc.)
# 2. ORDER BY, By DEFAULT ASC
# 3. LIKE (Wildcard -> For String), %, _
# 4. GROUP BY, HAVING (Aggregation Function)
# 5. (AVG, COUNT, SUM, MAX, MIN), (DISTINCT) -> unique
# 6. IN
# 7. BETWEEN
# 8. UNION, etc.

# Powerpoint presentation available on our github: "00. Presentations & Text Books/01. Electives 1 to 3"

In [14]:
# All Columns

query = "SELECT * FROM Summer"

result_sql = pd.read_sql_query(query, conn)
result_sql

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1896,Athens,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100M Freestyle,Gold
1,1896,Athens,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100M Freestyle,Silver
2,1896,Athens,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100M Freestyle For Sailors,Bronze
3,1896,Athens,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100M Freestyle For Sailors,Gold
4,1896,Athens,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100M Freestyle For Sailors,Silver
...,...,...,...,...,...,...,...,...,...
31160,2012,London,Wrestling,Wrestling Freestyle,"JANIKOWSKI, Damian",POL,Men,Wg 84 KG,Bronze
31161,2012,London,Wrestling,Wrestling Freestyle,"REZAEI, Ghasem Gholamreza",IRI,Men,Wg 96 KG,Gold
31162,2012,London,Wrestling,Wrestling Freestyle,"TOTROV, Rustam",RUS,Men,Wg 96 KG,Silver
31163,2012,London,Wrestling,Wrestling Freestyle,"ALEKSANYAN, Artur",ARM,Men,Wg 96 KG,Bronze
31164,2012,London,Wrestling,Wrestling Freestyle,"LIDBERG, Jimmy",SWE,Men,Wg 96 KG,Bronze

In [15]:
# Specific Columns

query = "SELECT City, Athlete FROM Summer"

result_sql = pd.read_sql_query(query, conn)
result_sql

         City                    Athlete
0      Athens              HAJOS, Alfred
1      Athens           HERSCHMANN, Otto
2      Athens          DRIVAS, Dimitrios
3      Athens         MALOKINIS, Ioannis
4      Athens         CHASAPIS, Spiridon
...       ...                        ...
31160  London         JANIKOWSKI, Damian
31161  London  REZAEI, Ghasem Gholamreza
31162  London             TOTROV, Rustam
31163  London          ALEKSANYAN, Artur
31164  London             LIDBERG, Jimmy

[31165 rows x 2 columns]

In [29]:
# AS (Alias)

query = "SELECT City, Athlete AS [Pangalan] FROM Summer"

result_sql = pd.read_sql_query(query, conn)
result_sql

         City                   Pangalan
0      Athens              HAJOS, Alfred
1      Athens           HERSCHMANN, Otto
2      Athens          DRIVAS, Dimitrios
3      Athens         MALOKINIS, Ioannis
4      Athens         CHASAPIS, Spiridon
...       ...                        ...
31160  London         JANIKOWSKI, Damian
31161  London  REZAEI, Ghasem Gholamreza
31162  London             TOTROV, Rustam
31163  London          ALEKSANYAN, Artur
31164  London             LIDBERG, Jimmy

[31165 rows x 2 columns]

In [30]:
# WHERE (AND)

query = "SELECT * FROM Summer "
query += "WHERE Event = '100M Freestyle' AND Medal = 'Gold'"

result_sql = pd.read_sql_query(query, conn)
result_sql

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1896,Athens,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100M Freestyle,Gold
1,1904,St Louis,Aquatics,Swimming,"HALMAY, Zoltan",HUN,Men,100M Freestyle,Gold
2,1908,London,Aquatics,Swimming,"DANIELS, Charles",USA,Men,100M Freestyle,Gold
3,1912,Stockholm,Aquatics,Swimming,"KAHANAMOKU, Duke Paoa",USA,Men,100M Freestyle,Gold
4,1912,Stockholm,Aquatics,Swimming,"DURACK, Fanny",ANZ,Women,100M Freestyle,Gold
5,1920,Antwerp,Aquatics,Swimming,"KAHANAMOKU, Duke Paoa",USA,Men,100M Freestyle,Gold
6,1920,Antwerp,Aquatics,Swimming,"BLEIBTREY, Ethelda",USA,Women,100M Freestyle,Gold
7,1924,Paris,Aquatics,Swimming,"WEISSMULLER, Johnny",USA,Men,100M Freestyle,Gold
8,1924,Paris,Aquatics,Swimming,"LACKIE, Ethel",USA,Women,100M Freestyle,Gold
9,1928,Amsterdam,Aquatics,Swimming,"WEISSMULLER, Johnny",USA,Men,100M Freestyle,Gold
10,1928,Amsterdam,Aquatics,Swimming,"OSIPOWICH, Albina Lucy",USA,Women,100M Freestyle,Gold
11,1932,Los Angeles,Aquatics,Swimming,"MIOYAZAKI, Yasuji",JPN,Men,100M Freestyle,Gold
12,1932,Los Angeles,Aquatics,Swimming,"MADISON, Helene",USA,Women,100M Freestyle,Gold
13,1936,Berlin,Aquatics,Swimming,"CSIK, Ferenc",HUN,Men,100M Freestyle,Gold
14,1936,Berlin,Aquatics,Swimming,"MASTENBROEK, Hendrika",NED,Women,100M Freestyle,Gold
15,1948,London,Aquatics,Swimming,"RIS, Walter Stephen",USA,Men,100M Freestyle,Gold
16,1948,London,Aquatics,Swimming,"ANDERSEN, Greta Marie",DEN,Women,100M Freestyle,Gold
17,1952,Helsinki,Aquatics,Swimming,"SCHOLES, Clark Currie",USA,Men,100M Freestyle,Gold
18,1952,Helsinki,Aquatics,Swimming,"SZÖKE, Katalin",HUN,Women,100M Freestyle,Gold
19,1956,Melbourne / Stockholm,Aquatics,Swimming,"HENRICKS, Jon Malcolm",AUS,Men,100M Freestyle,Gold
20,1956,Melbourne / Stockholm,Aquatics,Swimming,"FRASER, Dawn",AUS,Women,100M Freestyle,Gold
21,1960,Rome,Aquatics,Swimming,"DEVITT, John",AUS,Men,100M Freestyle,Gold
22,1960,Rome,Aquatics,Swimming,"FRASER, Dawn",AUS,Women,100M Freestyle,Gold
23,1964,Tokyo,Aquatics,Swimming,"SCHOLLANDER, Donald Arthur",USA,Men,100M Freestyle,Gold
24,1964,Tokyo,Aquatics,Swimming,"FRASER, Dawn",AUS,Women,100M Freestyle,Gold
25,1968,Mexico,Aquatics,Swimming,"WENDEN, Michael Vincent",AUS,Men,100M Freestyle,Gold
26,1968,Mexico,Aquatics,Swimming,"HENNE, Jane Margo",USA,Women,100M Freestyle,Gold
27,1972,Munich,Aquatics,Swimming,"SPITZ, Mark",USA,Men,100M Freestyle,Gold
28,1972,Munich,Aquatics,Swimming,"NEILSON, Alexandra Lynn",USA,Women,100M Freestyle,Gold
29,1976,Montreal,Aquatics,Swimming,"MONTGOMERY, James Paul",USA,Men,100M Freestyle,Gold
30,1976,Montreal,Aquatics,Swimming,"ENDER, Kornelia",GDR,Women,100M Freestyle,Gold
31,1980,Moscow,Aquatics,Swimming,"WOITHE, Jörg",GDR,Men,100M Freestyle,Gold
32,1980,Moscow,Aquatics,Swimming,"KRAUSE, Barbara",GDR,Women,100M Freestyle,Gold
33,1984,Los Angeles,Aquatics,Swimming,"GAINES, Ambrose Iv",USA,Men,100M Freestyle,Gold
34,1984,Los Angeles,Aquatics,Swimming,"HOGSHEAD, Nancy Lynn",USA,Women,100M Freestyle,Gold
35,1984,Los Angeles,Aquatics,Swimming,"STEINSEIFER, Carolyn",USA,Women,100M Freestyle,Gold
36,1988,Seoul,Aquatics,Swimming,"BIONDI, Matthew",USA,Men,100M Freestyle,Gold
37,1988,Seoul,Aquatics,Swimming,"OTTO, Kristin",GDR,Women,100M Freestyle,Gold
38,1992,Barcelona,Aquatics,Swimming,"POPOV, Alexander",EUN,Men,100M Freestyle,Gold
39,1992,Barcelona,Aquatics,Swimming,"ZHUANG, Yong",CHN,Women,100M Freestyle,Gold
40,1996,Atlanta,Aquatics,Swimming,"POPOV, Alexander",RUS,Men,100M Freestyle,Gold
41,1996,Atlanta,Aquatics,Swimming,"LE, Jingyi",CHN,Women,100M Freestyle,Gold
42,2000,Sydney,Aquatics,Swimming,"VAN DEN HOOGENBAND, Pieter",NED,Men,100M Freestyle,Gold
43,2000,Sydney,Aquatics,Swimming,"DE BRUIJN, Inge",NED,Women,100M Freestyle,Gold
44,2004,Athens,Aquatics,Swimming,"VAN DEN HOOGENBAND, Pieter",NED,Men,100M Freestyle,Gold
45,2004,Athens,Aquatics,Swimming,"HENRY, Jodie",AUS,Women,100M Freestyle,Gold
46,2008,Beijing,Aquatics,Swimming,"BERNARD, Alain",FRA,Men,100M Freestyle,Gold
47,2008,Beijing,Aquatics,Swimming,"STEFFEN, Britta",GER,Women,100M Freestyle,Gold
48,2012,London,Aquatics,Swimming,"ADRIAN, Nathan",USA,Men,100M Freestyle,Gold
49,2012,London,Aquatics,Swimming,"KROMOWIDJOJO, Ranomi",NED,Women,100M Freestyle,Gold

In [31]:
# WHERE (OR)

query = "SELECT * FROM Summer "
query += "WHERE Event = '100M Freestyle' OR Event = '200M Freestyle'"

result_sql = pd.read_sql_query(query, conn)
result_sql

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1896,Athens,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100M Freestyle,Gold
1,1896,Athens,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100M Freestyle,Silver
2,1900,Paris,Aquatics,Swimming,"RUBERL, Karl",AUT,Men,200M Freestyle,Bronze
3,1900,Paris,Aquatics,Swimming,"LANE, Frederick C.V.",AUS,Men,200M Freestyle,Gold
4,1900,Paris,Aquatics,Swimming,"HALMAY, Zoltan",HUN,Men,200M Freestyle,Silver
...,...,...,...,...,...,...,...,...,...
221,2012,London,Aquatics,Swimming,"PARK, Taehwan",KOR,Men,200M Freestyle,Silver
222,2012,London,Aquatics,Swimming,"SUN, Yang",CHN,Men,200M Freestyle,Silver
223,2012,London,Aquatics,Swimming,"SCHMITT, Allison",USA,Women,200M Freestyle,Gold
224,2012,London,Aquatics,Swimming,"MUFFAT, Camille",FRA,Women,200M Freestyle,Silver
225,2012,London,Aquatics,Swimming,"BARRATT, Bronte",AUS,Women,200M Freestyle,Bronze

In [35]:
# WHERE (NOT)

query = "SELECT * FROM Summer "
query += "WHERE NOT City = 'Athens'"

result_sql = pd.read_sql_query(query, conn)
result_sql

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1900,Paris,Aquatics,Swimming,"HALMAY, Zoltan",HUN,Men,1500M Freestyle,Bronze
1,1900,Paris,Aquatics,Swimming,"JARVIS, John Arthur",GBR,Men,1500M Freestyle,Gold
2,1900,Paris,Aquatics,Swimming,"WAHLE, Otto",AUT,Men,1500M Freestyle,Silver
3,1900,Paris,Aquatics,Swimming,"DROST, Johannes",NED,Men,200M Backstroke,Bronze
4,1900,Paris,Aquatics,Swimming,"HOPPENBERG, Ernst",GER,Men,200M Backstroke,Gold
...,...,...,...,...,...,...,...,...,...
29011,2012,London,Wrestling,Wrestling Freestyle,"JANIKOWSKI, Damian",POL,Men,Wg 84 KG,Bronze
29012,2012,London,Wrestling,Wrestling Freestyle,"REZAEI, Ghasem Gholamreza",IRI,Men,Wg 96 KG,Gold
29013,2012,London,Wrestling,Wrestling Freestyle,"TOTROV, Rustam",RUS,Men,Wg 96 KG,Silver
29014,2012,London,Wrestling,Wrestling Freestyle,"ALEKSANYAN, Artur",ARM,Men,Wg 96 KG,Bronze
29015,2012,London,Wrestling,Wrestling Freestyle,"LIDBERG, Jimmy",SWE,Men,Wg 96 KG,Bronze

In [20]:
# LIKE (Wildcard %)

query = "SELECT * FROM Summer "
query += " WHERE Athlete LIKE '%ak%' AND Gender = 'Men'"

result_sql = pd.read_sql_query(query, conn)
result_sql

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1896,Athens,Athletics,Athletics,"BLAKE, Arthur",USA,Men,1500M,Silver
1,1896,Athens,Athletics,Athletics,"VASILAKOS, Kharilaos",GRE,Men,Marathon,Silver
2,1896,Athens,Athletics,Athletics,"PERSAKIS, Ioannis",GRE,Men,Triple Jump,Bronze
3,1896,Athens,Fencing,Fencing,"PIERRAKOS-MAVROMICHALIS, Perikles",GRE,Men,Foil Individual,Bronze
4,1896,Athens,Fencing,Fencing,"KARAKALOS, Telemachos",GRE,Men,Sabre Individual,Silver
...,...,...,...,...,...,...,...,...,...
690,2012,London,Shooting,Shooting,"DAHLBY, Hakan",SWE,Men,Double Trap 150,Silver
691,2012,London,Wrestling,Wrestling Freestyle,"MAKHOV, Bilyal",RUS,Men,Wf 120KG,Bronze
692,2012,London,Wrestling,Wrestling Freestyle,"TANATAROV, Akzhurek",KAZ,Men,Wf 66 KG,Bronze
693,2012,London,Wrestling,Wrestling Freestyle,"JULFALAKYAN, Arsen",ARM,Men,Wg 74 KG,Silver
694,2012,London,Wrestling,Wrestling Freestyle,"KAZAKEVIC, Aleksandr",LTU,Men,Wg 74 KG,Bronze

In [21]:
# LIKE (Wildcard _) - Exact

query = "SELECT * FROM Summer WHERE Athlete LIKE '_____' AND Gender = 'Men'"

result_sql = pd.read_sql_query(query, conn)
result_sql

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1900,Paris,Aquatics,Swimming,CADET,FRA,Men,200M Team Swimming,Silver
1,1900,Paris,Croquet,Croquet,JOHIN,FRA,Men,Double,Gold
2,1900,Paris,Croquet,Croquet,JOHIN,FRA,Men,Individual 1 Ball,Silver
3,1904,St Louis,Lacrosse,Lacrosse,WOODS,USA,Men,Lacrosse,Silver
4,1904,St Louis,Lacrosse,Lacrosse,YOUNG,USA,Men,Lacrosse,Silver
5,1920,Antwerp,Equestrian,Vaulting,FIELD,FRA,Men,Figure Riding Individual,Silver
6,1920,Antwerp,Equestrian,Vaulting,FIELD,FRA,Men,Figure Riding Team,Silver
7,1980,Moscow,Equestrian,Dressage,IGROK,URS,Men,Individual,Silver
8,1980,Moscow,Equestrian,Dressage,IGROK,URS,Men,Team,Gold
9,1980,Moscow,Equestrian,Dressage,ALEKO,BUL,Men,Team,Silver
10,1980,Moscow,Equestrian,Jumping,TOPKI,URS,Men,Team,Gold
11,1996,Atlanta,Football,Football,SAVIO,BRA,Men,Football,Bronze
12,2008,Beijing,Football,Football,BRENO,BRA,Men,Football,Bronze
13,2008,Beijing,Football,Football,DIEGO,BRA,Men,Football,Bronze
14,2008,Beijing,Football,Football,LUCAS,BRA,Men,Football,Bronze
15,2008,Beijing,Football,Football,RENAN,BRA,Men,Football,Bronze
16,2012,London,Football,Football,GANSO,BRA,Men,Football,Silver
17,2012,London,Football,Football,OSCAR,BRA,Men,Football,Silver

In [22]:
# LIKE (Wildcard _)

query = "SELECT * FROM Summer WHERE Athlete LIKE 'A____R' AND Gender = 'Men'"

result_sql = pd.read_sql_query(query, conn)
result_sql

   Year     City     Sport Discipline Athlete Country Gender     Event   Medal
0  1996  Atlanta  Football   Football  ALDAIR     BRA    Men  Football  Bronze

In [40]:
# LIKE (Wildcard _ , %)

query = "SELECT * FROM Summer WHERE Athlete LIKE 'A_R%' AND Gender = 'Men'"

result_sql = pd.read_sql_query(query, conn)
result_sql

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1896,Athens,Aquatics,Swimming,"ANDREOU, Joannis",GRE,Men,1200M Freestyle,Silver
1,1896,Athens,Gymnastics,Artistic G.,"ANDRIAKOPOULOS, Nicolaos",GRE,Men,Rope Climbing,Gold
2,1896,Athens,Gymnastics,Artistic G.,"ANDRIAKOPOULOS, Nicolaos",GRE,Men,"Team, Parallel Bars",Silver
3,1900,Paris,Cricket,Cricket,"ATTRILL, W.T.",FRA,Men,Cricket,Silver
4,1904,St Louis,Cycling,Cycling Track,"ANDREWS, Arthur F.",USA,Men,25 Miles (40.232KM),Silver
...,...,...,...,...,...,...,...,...,...
95,2008,Beijing,Football,Football,"AMBROSE, Efe",NGR,Men,Football,Silver
96,2008,Beijing,Volleyball,Volleyball,"AMARAL, Dante",BRA,Men,Volleyball,Silver
97,2012,London,Fencing,Fencing,"ASPROMONTE, Valerio",ITA,Men,Foil Team,Gold
98,2012,London,Volleyball,Volleyball,"AMARAL, Dante",BRA,Men,Volleyball,Silver
99,2012,London,Wrestling,Wrestling Freestyle,"ANDRIITSEV, Valerii",UKR,Men,Wf 96 KG,Silver

In [42]:
# LIKE (Wildcard _ , %)

query = "SELECT * FROM Summer WHERE Athlete LIKE '%A__R' AND Gender = 'Men'"

result_sql = pd.read_sql_query(query, conn)
result_sql

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1904,St Louis,Rowing,Rowing,"SCHELL, Frank Reaner",USA,Men,Eight With Coxswain (8+),Gold
1,1904,St Louis,Tennis,Tennis,"WEST, Allen Tarwater",USA,Men,Doubles,Bronze
2,1912,Stockholm,Athletics,Athletics,"NELSON, Frank Thayer",USA,Men,Pole Vault,Silver
3,1912,Stockholm,Sailing,Sailing,"RODIONOV, Aleksandr",RU1,Men,10M,Bronze
4,1932,Los Angeles,Fencing,Fencing,"GEREVICH, Aladar",HUN,Men,Sabre Team,Gold
...,...,...,...,...,...,...,...,...,...
239,2012,London,Rowing,Rowing,"MARTIN, Damir",CRO,Men,Quadruple Sculls,Silver
240,2012,London,Wrestling,Wrestling Freestyle,"HATOS, Gabor",HUN,Men,Wf 74 KG,Bronze
241,2012,London,Wrestling,Wrestling Freestyle,"LASHGARI, Ehsan Naser",IRI,Men,Wf 84 KG,Bronze
242,2012,London,Wrestling,Wrestling Freestyle,"KAZAKEVIC, Aleksandr",LTU,Men,Wg 74 KG,Bronze
243,2012,London,Wrestling,Wrestling Freestyle,"EBRAHIM, Karam Mohamed Gaber",EGY,Men,Wg 84 KG,Silver

In [38]:
# ORDER BY (ASC, DEC)

query = "SELECT * FROM Summer "
query += "WHERE Event = '100M Freestyle' "
query += " AND Medal = 'Gold' AND Country = 'USA' AND Gender = 'Men' "
query += "ORDER BY Athlete DESC"

result_sql = pd.read_sql_query(query, conn)
result_sql

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1924,Paris,Aquatics,Swimming,"WEISSMULLER, Johnny",USA,Men,100M Freestyle,Gold
1,1928,Amsterdam,Aquatics,Swimming,"WEISSMULLER, Johnny",USA,Men,100M Freestyle,Gold
2,1972,Munich,Aquatics,Swimming,"SPITZ, Mark",USA,Men,100M Freestyle,Gold
3,1964,Tokyo,Aquatics,Swimming,"SCHOLLANDER, Donald Arthur",USA,Men,100M Freestyle,Gold
4,1952,Helsinki,Aquatics,Swimming,"SCHOLES, Clark Currie",USA,Men,100M Freestyle,Gold
5,1948,London,Aquatics,Swimming,"RIS, Walter Stephen",USA,Men,100M Freestyle,Gold
6,1976,Montreal,Aquatics,Swimming,"MONTGOMERY, James Paul",USA,Men,100M Freestyle,Gold
7,1912,Stockholm,Aquatics,Swimming,"KAHANAMOKU, Duke Paoa",USA,Men,100M Freestyle,Gold
8,1920,Antwerp,Aquatics,Swimming,"KAHANAMOKU, Duke Paoa",USA,Men,100M Freestyle,Gold
9,1984,Los Angeles,Aquatics,Swimming,"GAINES, Ambrose Iv",USA,Men,100M Freestyle,Gold
10,1908,London,Aquatics,Swimming,"DANIELS, Charles",USA,Men,100M Freestyle,Gold
11,1988,Seoul,Aquatics,Swimming,"BIONDI, Matthew",USA,Men,100M Freestyle,Gold
12,2012,London,Aquatics,Swimming,"ADRIAN, Nathan",USA,Men,100M Freestyle,Gold

In [44]:
# LIMIT

query = "SELECT * FROM Summer WHERE Medal = 'Gold' AND Country = 'USA'"
query += " AND Gender = 'Women' ORDER BY Athlete DESC LIMIT 5"

result_sql = pd.read_sql_query(query, conn)
result_sql

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,2004,Athens,Fencing,Fencing,"ZAGUNIS, Mariel",USA,Women,Sabre Individual,Gold
1,2008,Beijing,Fencing,Fencing,"ZAGUNIS, Mariel",USA,Women,Sabre Individual,Gold
2,1904,St Louis,Archery,Archery,"WOODRUFF, Laura",USA,Women,Teams Fita Round,Gold
3,1920,Antwerp,Aquatics,Swimming,"WOODBRIDGE, Margaret",USA,Women,4X100M Freestyle Relay,Gold
4,1984,Los Angeles,Basketball,Basketball,"WOODARD, Lynette",USA,Women,Basketball,Gold

In [47]:
# LIMIT

query = "SELECT * FROM Summer WHERE Medal = 'Gold' AND Country = 'USA'"
query += " AND Gender = 'Women' ORDER BY Athlete DESC LIMIT 0, 3"

result_sql = pd.read_sql_query(query, conn)
result_sql

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,2004,Athens,Fencing,Fencing,"ZAGUNIS, Mariel",USA,Women,Sabre Individual,Gold
1,2008,Beijing,Fencing,Fencing,"ZAGUNIS, Mariel",USA,Women,Sabre Individual,Gold
2,1904,St Louis,Archery,Archery,"WOODRUFF, Laura",USA,Women,Teams Fita Round,Gold

In [49]:
# GROUP BY, Aggregation Function, COUNT, MAX, MIN, AVG, SUM)

query = "SELECT Country, COUNT(Medal) AS [Medal_Count] "
query += "FROM Summer WHERE COUNTRY = 'PHI' "
query += "GROUP BY Country ORDER BY Medal_Count DESC"

result_sql = pd.read_sql_query(query, conn)
result_sql

  Country  Medal_Count
0     PHI            9

In [50]:
# GROUP BY, HAVING (Aggregation Function, COUNT, MAX, MIN, AVG, SUM)

query = "SELECT Country, Medal, COUNT(Medal) AS [Medal_Count] FROM Summer "
query += "GROUP BY Medal, Country "
query += "HAVING (Country = 'PHI') ORDER BY Medal_Count DESC"

result_sql = pd.read_sql_query(query, conn)
result_sql

  Country   Medal  Medal_Count
0     PHI  Bronze            7
1     PHI  Silver            2

In [25]:
# DISTINCT

query = "SELECT DISTINCT(Country) FROM Summer"
result_sql = pd.read_sql_query(query, conn)
result_sql

    Country
0       HUN
1       AUT
2       GRE
3       USA
4       GER
..      ...
143     BOT
144     MNE
145     CYP
146     SGP
147     GAB

[148 rows x 1 columns]

In [26]:
# DISTINCT

query = "SELECT COUNT(DISTINCT(Country)) AS 'Participating Country' FROM Summer"
result_sql = pd.read_sql_query(query, conn)
result_sql

   Participating Country
0                    147

In [60]:
# IN (Shorthand OR), Can be used in WHERE or HAVING

query = "SELECT Country, COUNT(Medal) FROM Summer GROUP BY Country "
query += "HAVING Country IN ('USA', 'AUS', 'CAN')"

result_sql = pd.read_sql_query(query, conn)
result_sql

  Country  COUNT(Medal)
0     AUS          1189
1     CAN           649
2     USA          4585

In [62]:
# BETWEEN (Shorthand for Ranges), Can be used in WHERE or HAVING

query = "SELECT Year, Athlete, Event FROM Summer "
query += " WHERE (Year BETWEEN 1896 AND 1912) AND (Event = '100M Freestyle')"
result_sql = pd.read_sql_query(query, conn)
result_sql

    Year                Athlete           Event
0   1896          HAJOS, Alfred  100M Freestyle
1   1896       HERSCHMANN, Otto  100M Freestyle
2   1904        LEARY, J. Scott  100M Freestyle
3   1904         HALMAY, Zoltan  100M Freestyle
4   1904       DANIELS, Charles  100M Freestyle
5   1908     JULIN, Harald S.A.  100M Freestyle
6   1908       DANIELS, Charles  100M Freestyle
7   1908         HALMAY, Zoltan  100M Freestyle
8   1912       HUSZAGH, Kenneth  100M Freestyle
9   1912  KAHANAMOKU, Duke Paoa  100M Freestyle
10  1912           HEALY, Cecil  100M Freestyle
11  1912       FLETCHER, Jennie  100M Freestyle
12  1912          DURACK, Fanny  100M Freestyle
13  1912      WYLIE, Wilhelmina  100M Freestyle

In [66]:
# UNION (Combine)

query = "SELECT Year, Athlete, Event FROM Summer "
query += "WHERE Year BETWEEN 1896 AND 1912 AND (Event = '100M Freestyle')"
query += "UNION "
query += "SELECT Year, Athlete, Event FROM Summer "
query += "WHERE Year BETWEEN 1896 AND 1912 AND (Event = '200M Freestyle')"

result_sql = pd.read_sql_query(query, conn)
result_sql

    Year                Athlete           Event
0   1896          HAJOS, Alfred  100M Freestyle
1   1896       HERSCHMANN, Otto  100M Freestyle
2   1900         HALMAY, Zoltan  200M Freestyle
3   1900   LANE, Frederick C.V.  200M Freestyle
4   1900           RUBERL, Karl  200M Freestyle
5   1904       DANIELS, Charles  100M Freestyle
6   1904       DANIELS, Charles  200M Freestyle
7   1904        GAILEY, Francis  200M Freestyle
8   1904         HALMAY, Zoltan  100M Freestyle
9   1904        LEARY, J. Scott  100M Freestyle
10  1904           RAUSCH, Emil  200M Freestyle
11  1908       DANIELS, Charles  100M Freestyle
12  1908         HALMAY, Zoltan  100M Freestyle
13  1908     JULIN, Harald S.A.  100M Freestyle
14  1912          DURACK, Fanny  100M Freestyle
15  1912       FLETCHER, Jennie  100M Freestyle
16  1912           HEALY, Cecil  100M Freestyle
17  1912       HUSZAGH, Kenneth  100M Freestyle
18  1912  KAHANAMOKU, Duke Paoa  100M Freestyle
19  1912      WYLIE, Wilhelmina  100M Freestyle