# SQL in Python

In [1]:
# Imports

import sqlite3
import pandas as pd

In [2]:
# Load data

data = pd.read_csv('https://raw.githubusercontent.com/renatomaaliw3/public_files/master/Data%20Sets/summer.csv')
data.head(5)

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1896,Athens,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100M Freestyle,Gold
1,1896,Athens,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100M Freestyle,Silver
2,1896,Athens,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100M Freestyle For Sailors,Bronze
3,1896,Athens,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100M Freestyle For Sailors,Gold
4,1896,Athens,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100M Freestyle For Sailors,Silver

In [3]:
# Connect to an in memory SQLite Database

conn = sqlite3.connect(':memory')

In [4]:
# Write the DataFrame to the Database

data.to_sql('Summer', conn, index = False)

31165

In [56]:
# Execute a SQL Query

query = "SELECT COUNT(DISTINCT Athlete) AS Names FROM Summer WHERE Event = '100M Freestyle'"
result_sql = pd.read_sql_query(query, conn)

In [57]:
# Display the Query Results

result_sql

   Names
0    127

In [72]:
# Python Code?

data.query("Event == '100M Freestyle'").nunique()

Year           26
City           22
Sport           1
Discipline      1
Athlete       127
Country        24
Gender          2
Event           1
Medal           3
dtype: int64

In [ ]:
# Notes

# 0. AS
# 1. WHERE
# 2. ORDER BY
# 3. LIKE
# 4. GROUPBY, HAVING
# 5. (AVG, COUNT, SUM), (DISTINCT)